version: "3.8"
services:
  db:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ent
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      interval: 0.5s
      retries: 40
      test: |
        pg_isready -U postgres
    networks:
      - common
networks:
  common:
volumes:
  db-data:
